export const ROUTE_URL = {
  HOME: "",
  DASHBOARD: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  ABOUT: "/about",
  CONTACT: "/contact",
  UI: "/ui",
  NOT_ALLOWED: "/not-allowed",
  SOCIAL_MEDIA_MANAGEMENT: "/social-media",
  ADMIN: {
    BASE: "/admin",
    ORGANIZATION_UNITS: "organization-units",
    TENANT: {
      BASE: "/tenant",
      TENANT_LIST: "",
      TENANT_DETAIL: ":id",
      TENANT_DETAIL_EDIT: "edit/:id",
      TENANT_DETAIL_ADD: "add",
    },
    ROLE: {
      BASE: "/role",
      ROLE_LIST: "",
      ROLE_DETAIL: ":id",
      ROLE_DETAIL_EDIT: "edit/:id",
      ROLE_DETAIL_ADD: "add",
    },
    USER: {
      BASE: "/user",
      USER_LIST: "",
      USER_DETAIL: ":id",
      USER_DETAIL_EDIT: "edit/:id",
      USER_DETAIL_ADD: "add",
      USER_PERMISSIONS: "permissions/:id",
    },
    SUBSCRIPTION_MANAGEMENT: "subscription-management",
  },
  CULTIVATION: "/cultivation",
  CULTIVATION_CREATE: "/cultivation/create",
  CULTIVATION_EDIT: "/cultivation/edit/:id",
  EXPENDITURE: "/expenditure",
  EXPENDITURE_CREATE: "/expenditure/create",
  EXPENDITURE_EDIT: "/expenditure/edit/:id",
  FARMERS: "/farmer",
  FARMER_CREATE: "/farmer/create",
  FARMER_EDIT: "/farmer/edit/:id",
  CRAFT: "/craft",
  CRAFT_CREATE: "/craft/create",
  CRAFT_EDIT: "/craft/edit/:id",
  CATEGORY: "/category",
  CATEGORY_CREATE: "/category/create",
  CATEGORY_EDIT: "/category/edit/:id",
};
