export enum ROUTE_URL {
    HOME = "",
    DASHBOARD = "/",
    LOGIN = "/login",
    REGISTER = "/register",
    ABOUT = "/about",
    CONTACT = "/contact",
    UI = "/ui",
    ADMIN = "/admin",
    ORGANIZATION_UNITS = "/organization-units",
    ROLES = "/roles",
    USERS = "/users",
    USER_DETAIL = "/users/:id",
    USER_DETAIL_EDIT = "/users/edit/:id",
}