export enum ROUTE_URL {
  HOME = "",
  DASHBOARD = "/",
  LOGIN = "/login",
  REGISTER = "/register",
  ABOUT = "/about",
  CONTACT = "/contact",
  UI = "/ui",
  ADMIN = "/admin",
  ORGANIZATION_UNITS = "/organization-units",
  ROLES = "/role",
  ROLE_DETAIL = "/role/:id",
  ROLE_DETAIL_EDIT = "/role/edit/:id",
  USERS = "/user",
  USER_DETAIL = "/user/:id",
  USER_DETAIL_EDIT = "/user/edit/:id",
}
